--------------------------------------------------------
--  DDL for Table ALLOCATION_TB
--------------------------------------------------------

  CREATE TABLE "FTA_USER"."ALLOCATION_TB" 
   (	"ALLOCATION_ID" NUMBER(26,0), 
	"SHIFT_ID" NUMBER(26,0), 
	"EMPLOYEE_ID" VARCHAR2(26 BYTE), 
	"DAY" DATE, 
	"WEEK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ALLOCATION_TB
--------------------------------------------------------

  ALTER TABLE "FTA_USER"."ALLOCATION_TB" MODIFY ("DAY" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table EMP_PREFERENCE_TB
--------------------------------------------------------

  CREATE TABLE "FTA_USER"."EMP_PREFERENCE_TB" 
   (	"EMPLOYEE_ID" NUMBER, 
	"PREFERENCE_ID" VARCHAR2(26 BYTE), 
	"VALUE" VARCHAR2(100 BYTE), 
	"PRIORITY" NUMBER(38,0), 
	"TEMP_HARD_CONSTRAINT" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;



--------------------------------------------------------
--  DDL for Table EMPLOYEE_TB
--------------------------------------------------------

  CREATE TABLE "FTA_USER"."EMPLOYEE_TB" 
   (	"EMPLOYEE_ID" NUMBER, 
	"NAME" VARCHAR2(26 BYTE), 
	"SKILL" VARCHAR2(26 BYTE), 
	"HOURLY_RATE" NUMBER(38,13)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_TB
--------------------------------------------------------

  ALTER TABLE "FTA_USER"."EMPLOYEE_TB" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table FAIRNESS_BANK_TB
--------------------------------------------------------

  CREATE TABLE "FTA_USER"."FAIRNESS_BANK_TB" 
   (	"EMPLOYEE_ID" NUMBER, 
	"VIOLATIONS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FAIRNESS_BANK_TB
--------------------------------------------------------

  ALTER TABLE "FTA_USER"."FAIRNESS_BANK_TB" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table PREFERENCE_TB
--------------------------------------------------------

  CREATE TABLE "FTA_USER"."PREFERENCE_TB" 
   (	"PREFERENCE_ID" VARCHAR2(26 BYTE), 
	"PREFERENCE_NAME" VARCHAR2(128 BYTE), 
	"HARD_CONSTRAINT" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


--------------------------------------------------------
--  DDL for Table REQUIREMENTS_TB
--------------------------------------------------------

  CREATE TABLE "FTA_USER"."REQUIREMENTS_TB" 
   (	"SHIFT_ID" NUMBER(38,0), 
	"DAY" NUMBER(38,0), 
	"SHIFT" NUMBER(38,0), 
	"KITCHEN" NUMBER(38,13), 
	"COUNTER" NUMBER(38,0), 
	"CLEANING" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


